@baseUrl = http://localhost:4000/api

### get all users
GET {{baseUrl}}/users

### sign up
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
    "username": "ThaiHoang",
    "email": "thaihoang@gmail.com",
    "password": "abc123"
}