@baseUrl = http://localhost:4000/api

### get all users
GET {{baseUrl}}/users

### sign up
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
    "username": "TH12",
    "email": "thaihoang12312311@gmail.com",
    "password": "123123",
}