@baseUrl = http://localhost:4000/api


# ---------------- User onboarding API -------------------

### get all users
GET {{baseUrl}}/users

### sign up
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
    "username": "TT123",
    "email": "thait123@gmail.com",
    "password": "123123"
}

### verify verification code
POST {{baseUrl}}/verify-email
Content-Type: application/json

{
    "email": "thaihoang20112k3@gmail.com",
    "code": "1211"
}


### verify verification code
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "thaihoang20112k3@gmail.com",
    "password": "123123"
}


# ---------------- Challenge API -------------------

### get all challenges
GET {{baseUrl}}/challenges
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRoYWlob2FuZzIwMTEyazNAZ21haWwuY29tIiwiaWF0IjoxNzA2NzYzOTY0LCJleHAiOjE3MDY3NjM5OTR9.TJzGWjqBBupz58tFSDt_cui48X-tGtbKcMj-rn_0Lm8


### create new challenge
POST {{baseUrl}}/challenge/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRoYWlob2FuZzIwMTEyazNAZ21haWwuY29tIiwiaWF0IjoxNzA2OTI5NDc4LCJleHAiOjE3MDY5Mjk1MDh9.sffoDwFtrfGZWSPzIG46RKrLriwOxuv80VDXbBnzIgo

{
    "title": "Lam sach bien My Khe",
    "images_path": "firebase.cloud",
    "description": "Lam sach bien tu 2km -> 14km",
    "points_reward": 5
}

### update challenge
POST {{baseUrl}}/challenge/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRoYWlob2FuZzIwMTEyazNAZ21haWwuY29tIiwiaWF0IjoxNzA2OTMxMzExLCJleHAiOjE3MDcwMzkzMTF9.d6ZNzQVAwYSBPS6hoetE75TjnDPkSUM6S00gQVfnLVo

{
    "id": "65bdad62e331cf8e35af720d",
    "title": "Lam sach bien My Khe 2",
    "images_path": "firebase.cloud.com",
    "description": "Lam sach bien tu 2km -> 16km",
    "points_reward": 3
}

### get all challenges by approved status
GET {{baseUrl}}/challenge/approved


### get all challenges by pending status
GET {{baseUrl}}/challenge/pending


### get all challenges by rejected status
GET {{baseUrl}}/challenge/rejected


# ---------------- Send verification code -------------------

### send mail
POST {{baseUrl}}/send-verification-code
Content-Type: application/json

{
    "email": "thaihoang20112k3@gmail.com"
}