version: "3.9"
services:
  web-api:
    build: ../
    ports:
      - "3000:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    env_file: ./.env

  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    env_file: ./.env

volumes:
  mongodb: {}