@Library('ezc-jenkins-library@init') _
Map buildSetting
String tagName

pipeline {
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10', artifactNumToKeepStr: '10', artifactDaysToKeepStr: '10'))
    }
    agent {
        label "master"
    }

    parameters {
        booleanParam name: 'Release', defaultValue: false, description: 'Build release version'
        booleanParam name: 'ScanSonar', defaultValue: false, description: 'Scan Sonarqube for CodeQuality'
        booleanParam name: 'Deploy', defaultValue: false, description: 'Deploy the version'
    }

    stages {
        stage('Prepare') {
            agent {
                docker {
                    image 'node:20.11.0-alpine3.19'
                    reuseNode true
                }
            }
            steps {
                script {
                    checkout scm
                    common.populateBuildOption(buildSetting)
                    sh 'node --version'

                    print "${GIT_BRANCH}"
                    tagName = "${GIT_BRANCH}"
                    if ("${GIT_BRANCH}"=="master") {
                        tagName = "latest"
                    } else if ("${GIT_BRANCH}"=="develop") {
                        tagName = "develop"
                    }
                    print "TODO: Get git repo info"
                    print "TODO: Get app build info"
                }
            }
        }

        stage('Tag release') {
            agent {
                docker {
                    image 'node:20.11.0-alpine3.19'
                    reuseNode true
                }
            }
            when {
                expression {
                    expression { params.Release.toBoolean() }
                }
            }
            steps {
                print 'TODO: Tag version on Github'
            }
        }

        stage('build develop') {
            agent {
                docker {
                    image 'node:21-alpine'
                    reuseNode true
                }
            }
            when {
                expression {
                    expression { params.Release.toBoolean() }
                }
            }
            steps {
                sh 'npm ci'
            }
        }

        stage('Code Quality') {
            agent {
                docker {
                    image 'node:20.11.0-alpine3.19'
                    reuseNode true
                }
            }
            when {
                expression {
                    expression { params.ScanSonar.toBoolean() }
                }
            }
            steps {
                script {
                    print 'TODO: Add publish command'
                    common.cmd "echo Test lib"
                }
            }
        }

        stage('Build Docker Image') {
            when {
                anyOf {
                    allOf {
                        expression { params.Release.toBoolean() }
                        expression { !git.isPR(GIT_BRANCH) }
                    }
                    branch 'develop'
                    branch 'master'
                }
            }
            steps {
                script {
                    sh 'export DOCKER_CREDENTIAL_CONFIG=/usr/local/bin/.docker/config.json'

                    dockerOptions = "--build-arg GIT_COMMIT=${GIT_COMMIT} --build-arg GIT_URL=${GIT_URL} --build-arg GIT_BRANCH=${GIT_BRANCH}"
                    dockerOptions = dockerOptions + " --build-arg BUILD_NUMBER=${BUILD_NUMBER} --build-arg BUILD_URL=${BUILD_URL}"
                    dockerOptions = dockerOptions + " --build-arg APP_NAME=ezc-backend"
                    sh "docker build ${dockerOptions} -t opsifydev/ezc-backend:${tagName} -f Dockerfile ."
                }
            }
        }

        stage('Push Image to Dockerhub') {
            when {
                anyOf {
                    allOf {
                        expression { params.Release.toBoolean() }
                        expression { !git.isPR(GIT_BRANCH) }
                    }
                    branch 'develop'
                    branch 'master'
                }
            }
            steps {
                script {
                    withDockerRegistry([credentialsId: "GreenBee_DockerHub", url: '']) {
                        sh "docker push opsifydev/ezc-backend:${tagName}"
                    }
                }
            }
        }

        stage('deployments') {
            parallel {
                stage('deploy test') {
                    when {
                        anyOf {
                            allOf {
                                expression { params.Release.toBoolean() }
                                expression { !git.isPR(GIT_BRANCH) }
                            }
                            branch 'develop'
                        }
                    }
                    steps {
                        withCredentials([string(credentialsId: 'GreenBee_Test-DeployHook', variable: 'WEBHOOK')]) { //set SECRET with the credential content
                            sh "curl -X POST ${WEBHOOK}?TAG=${tagName}"
                        }
                    }
                }
                stage('deploy demo') {
                    when {
                        anyOf {
                            allOf {
                                expression { params.Release.toBoolean() }
                                expression { !git.isPR(GIT_BRANCH) }
                            }
                            branch 'master'
                        }
                    }
                    steps {
                        echo 'demo deployment done'
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                print 'TODO: Notify GoogleChat build status'
                // common.notifyGoogleChat("This is test message from EZC GreenBee CICD Chatbot")
            }
        }
        cleanup {
            cleanWs()
        }
    }
}