name: EZC-Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v3
      with:
        url: https://vault.opsify.dev
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          greenbee/data/cicd DockerHub_Username | DOCKERHUB_USERNAME ;
          greenbee/data/cicd DockerHub_Password | DOCKERHUB_TOKEN ;

    - uses: actions/checkout@v4
    - name: Build NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '21.x'
        # cache: 'npm'
    - run: npm install
    # - run: npm run build --if-present
    # - run: npm run test --if-present
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    -
      name: Build and Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: opsifydev/ezc-backend:develop

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.opsify.dev
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            greenbee/data/cicd DeployHook-TestURL | DEPLOYHOOK_TEST_URL ;

      - name: Webhook
        uses: zzzze/webhook-trigger@master
        with:
          # data: "{\"event_type\":\"build\"}"
          # webhook_url: "${{ env.DEPLOYHOOK_TEST_URL }}?TAG=develop"
          webhook_url: "${{ env.DEPLOYHOOK_TEST_URL }}?TAG=${GITHUB_REF##*/}"
          # options: "-H \"Accept: application/vnd.github.everest-preview+json\" -H \"Authorization: token ${{ secrets.TOKEN }}\""
    needs: build