name: EZC-Backend CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Import Secrets
      uses: hashicorp/vault-action@v2
      with:
        url: https://vault.opsify.dev
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          credentials/data/jenkins GreenBee_DockerHub_Username | DOCKERHUB_USERNAME ;
          credentials/data/jenkins GreenBee_DockerHub_Password | DOCKERHUB_TOKEN ;

    - uses: actions/checkout@v4
    - name: Build NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm ci
    # - run: npm run build --if-present
    # - run: npm run test --if-present

  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.opsify.dev
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            credentials/data/jenkins GreenBee_DockerHub_Username | DOCKERHUB_USERNAME ;
            credentials/data/jenkins GreenBee_DockerHub_Password | DOCKERHUB_TOKEN ;
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: opsifydev/ezc-backend:develop
    needs: build

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Webhook
  #       uses: zzzze/webhook-trigger@master
  #       with:
  #         data: "{\"event_type\":\"build\"}"
  #         webhook_url: ${{ secrets.WEBHOOK_URL }}
  #         options: "-H \"Accept: application/vnd.github.everest-preview+json\" -H \"Authorization: token ${{ secrets.TOKEN }}\""