name: EZC-Backend

on:
  push:
    branches: [ "develop", "ezc-backend-ci"]
  pull_request:
    branches: [ "develop", "ezc-backend-ci"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: Build NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '21.x'
        cache: 'npm'
    - run: npm ci
    # - run: npm run build --if-present
    # - run: npm run test --if-present
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.GREENBEE_DOCKERHUB_USERNAME }}
        password: ${{ secrets.GREENBEE_DOCKERHUB_TOKEN }}
    -
      name: Get Gitbranch
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    -
      name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: opsifydev/ezc-backend:${{ env.BRANCH }}

  deploy:

    runs-on: ubuntu-latest
    steps:

      - name: Webhook
        uses: zzzze/webhook-trigger@master
        with:
          # data: "{\"event_type\":\"build\"}"
          webhook_url: "${{ secrets.GREENBEE_DEPLOYHOOK_TEST_URL }}?TAG=${{ env.BRANCH }}"
          # webhook_url: "${{ env.DEPLOYHOOK_TEST_URL }}?TAG=${GITHUB_REF##*/}"
          # options: "-H \"Accept: application/vnd.github.everest-preview+json\" -H \"Authorization: token ${{ secrets.TOKEN }}\""
    needs: build